components:
- name: ElasticsearchDocumentStore
  params:
    index: eval_docs
  type: ElasticsearchDocumentStore
- name: retriever
  params:
    document_store: ElasticsearchDocumentStore
    top_k: 1
  type: BM25Retriever
- name: generator
  params:
    max_new_tokens: 100
    prompt_messages:
    - content: 'Χρησιμοποιώντας τις πληροφορίες που περιέχονται στο "Κείμενο", δώσε μια ολοκληρωμένη απάντηση στην "Ερώτηση". Εάν δεν μπορείς να απαντήσεις με βάση το "Κείμενο", απάντα "Δεν γνωρίζω".'
      role: system
    - content: '"Ερώτηση": {query}; "Κείμενο": {join(documents)}'
      role: user
    temperature: 0.4
    top_p: 0.5
  type: Generator
pipelines:
- name: query
  nodes:
  - inputs:
    - Query
    name: retriever
  - inputs:
    - retriever
    name: generator
version: 1.25.5
