{
    "version": "ignore",
    "components": [
        {  
            "name": "fine_tuned_Reader",  
            "type": "FARMReader",  
            "params": {"no_ans_boost": -10, "model_name_or_path": "/model"},
        },
        {
            "name": "Sparse_Retriever",
            "type": "BM25Retriever",
            "params": {
                "document_store": "ES_DocumentStore", 
                "custom_query": None,
            },
        },
        {
            "name": "Dense_Retriever"
            "type": "EmbeddingRetriever",
            "params": {
                "document_store": "ES_DocumentStore",
                "embedding_model": "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"
                "model_format": "sentence-transformers"
            }
        }
        {"name": "ES_DocumentStore", "type": "ElasticsearchDocumentStore", "params": {"index": "haystack_test", "similarity":"dot_product", "embedding_dim": 768}},
        {"name": "TextFileConverter", "type": "TextConverter"},
        {"name": "Preprocessor", "type": "Preprocessor", "params": {"language": "el"}}
        ],
    "pipelines": [
        {  
            "name": "extractive_query_pipeline",  
            "nodes": [
                {"name": "Sparse_Retriever", "inputs": ["Query"]},
                {"name": "fine_tuned_Reader", "inputs": ["Sparse_Retriever"]},
            ],
        },
        {
            "name": "indexing",
            "nodes": [
                {"name": "TextFileConverter", "inputs": ["File"]},
                {"name": "Preprocessor", "inputs": ["TextFileConverter"]},
                {"name": "Sparse_Retriever", "inputs": ["Preprocessor"]}
                {"name": "ES_DocumentStore", "inputs": ["Sparse_Retriever"]}
            ]
        }
    ],
}