services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.17.6"
    ports:
      - 9200:9200
    restart: on-failure
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - network.host=0.0.0.0
    networks:
      - esnet
    healthcheck:
      test: curl --fail http://localhost:9200/_cat/health || exit 1
      interval: 10s
      timeout: 1s
      retries: 10

  rest-api:
    build:
      context: .
    ports:
      - 8000:8000
    restart: on-failure
    environment:
      - DOCUMENTSTORE_PARAMS_HOST=elasticsearch
      - TOKENIZERS_PARALLELISM=false
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - esnet

networks:
  esnet:
    driver: bridge
